---
title: "figure 1"
author: "Pavitra Roychoudhury"
date: "2023-07-15"
output: html_document
---

panels for Figure 1
Fig 1 shows effect of filtering
```{r}
rm(list=ls())
library(Seurat)
library(tidyverse)
options(dplyr.width=Inf)
library(cowplot); options(scipen = 999)

all3<-readRDS('./seurat_analysis_all3.rds')

plot_data<-data.frame(lib=all3$lib,nFeature_RNA=all3$nFeature_RNA,nCount_RNA=all3$nCount_RNA,percent.mt=all3$percent.mt)
plot_data$lib<-factor(plot_data$lib,levels = c('Uninf','Inf1','Inf2'))
p1<-ggplot(plot_data,aes(x=lib,y=nFeature_RNA))+
  xlab('')+ylab('Number of observed genes per cell')+
  geom_jitter(size=0.5,colour='grey50')+
  geom_violin(aes(fill=lib),scale = 'width',alpha=0.8)+ 
  scale_fill_manual(values=c('Uninf'='blue','Inf1'='red','Inf2'='red4'))+
  scale_x_discrete(labels=c('Uninf'='Uninf-1','Inf1'='Inf-1','Inf2'='Inf-2'))+
  ylim(0,11500)+
  theme_classic()+
  theme(legend.position = 'none')
p2<-ggplot(plot_data,aes(x=lib,y=log10(nCount_RNA)))+
  xlab('')+ylab('Log10 Number of molecules per cell')+
  geom_jitter(size=0.5,colour='grey50')+
  geom_violin(aes(fill=lib),scale = 'width',alpha=0.8)+
  scale_fill_manual(values=c('Uninf'='blue','Inf1'='red','Inf2'='red4'))+
  scale_x_discrete(labels=c('Uninf'='Uninf-1','Inf1'='Inf-1','Inf2'='Inf-2'))+
  # scale_y_continuous(limits=c(2.5,5.5),breaks=c(2.5,3.5,4.5,5.5))+
  ylim(0,6)+
  theme_classic()+
  theme(legend.position = 'none')
p3<-ggplot(plot_data,aes(x=lib,y=percent.mt))+
  xlab('')+ylab('% mitochondrial reads')+
  geom_jitter(size=0.5,colour='grey50')+
  geom_violin(aes(fill=lib),scale = 'width',alpha=0.8)+ 
  scale_fill_manual(values=c('Uninf'='blue','Inf1'='red','Inf2'='red4'))+
  scale_x_discrete(labels=c('Uninf'='Uninf-1','Inf1'='Inf-1','Inf2'='Inf-2'))+
  theme_classic()+ylim(-1,100)+
  theme(legend.position = 'none')
rm(plot_data)
```

Figure for paper: testing different levels of mt filtering
```{r}
all3_10<-subset(
  all3_prefilter,
  percent.mt < 10 & nFeature_RNA > 300 & nFeature_RNA < 9000
) 

all3_15<-subset(
  all3_prefilter,
  percent.mt < 15 & nFeature_RNA > 300 & nFeature_RNA < 9000
) 

all3_20<-subset(
  all3_prefilter,
  percent.mt < 20 & nFeature_RNA > 300 & nFeature_RNA < 9000
) 

all3_25<-subset(
  all3_prefilter,
  percent.mt < 25 & nFeature_RNA > 300 & nFeature_RNA < 9000
) 

plot_data2<-all3_prefilter@meta.data %>% group_by(lib) %>% summarize(n_prefilter=n()) %>% as.data.frame() %>% 
  left_join(all3_10@meta.data %>% group_by(lib) %>% summarize(n_10=n()) %>% as.data.frame(),by='lib') %>% 
  left_join(all3_15@meta.data %>% group_by(lib) %>% summarize(n_15=n()) %>% as.data.frame(),by='lib') %>% 
  left_join(all3_20@meta.data %>% group_by(lib) %>% summarize(n_20=n()) %>% as.data.frame(),by='lib') %>% 
  left_join(all3_25@meta.data %>% group_by(lib) %>% summarize(n_25=n()) %>% as.data.frame(),by='lib') %>% 
  pivot_longer(cols = n_prefilter:n_25,names_to = 'filter_perc',names_prefix = 'n_',values_to = 'cells')
plot_data2$filter_perc<-factor(plot_data2$filter_perc,
                               levels=c('prefilter',25,20,15,10))
plot_data2$lib<-factor(plot_data2$lib,
                       levels = c('Uninf','Inf1','Inf2'),
                       labels = c('Uninf-1','Inf-1','Inf-2'))
  
p4<-ggplot(plot_data2,aes(x=filter_perc,y=cells,fill=lib))+
  geom_bar(position = 'stack',stat='identity',colour='black')+
  scale_fill_manual(values=c('Uninf-1'='blue','Inf-1'='red','Inf-2'='red4'))+
  theme_classic()+
  theme(legend.position = c(0.8,0.8),
        legend.title = element_blank())+
  ylim(0,30000)+
  xlab('mt filter level (%)')+ ylab('Number of cells')

pdf('./figures_for_ppr/Fig1_matchAxesLims.pdf',width = 8,height=8)
plot_grid(p1,p2,p3,p4,nrow = 2)
dev.off()
write_csv(plot_data2,'./figures_for_ppr/Mt_filtering_levels.csv')

pdf('./figures_for_ppr/Fig1_matchAxesLims.pdf',width = 8,height=8)
plot_grid(p1,p2,p3,p4,nrow = 2)
dev.off()

```
```

